### ISSUE TITLE
Element

### ISSUE THREAD

**Issue by bojanasofronovic** [MilicaVulic/JSDGenerator#6]
@MilicaVulic 
Element u gramatici ne posmatrati kao pojedinican oblik, recimo "stolica". Neka to bude lista oblika koja ce se iscrtavati, a ako zelimo da nacrtamo stolicu sa sedistem i naslonom onda mozemo da imamo poseban painter za to.

**Comment by 0xMilica** [comment]
Pogledaj model, razmatrala sam to kad sam kreirala projekat i u prvom komitu je to vec reseno
